appName: DistributedAsyncTasksWithRestful
logLevel: WARN

DEBUG: True
TESTING: True

#routes:

database:
  mongo:
    host: localhost
    port: 27017
    db: books

  redis:
    host: localhost
    port: 6379
    db: books

worker-queue:
  rabbitmq:
    host: localhost
    username: admin
    password: yourmqpasswordhere