version: '3.5'

services:
  mongodb:
    hostname: localhost
    container_name: mongo-db
    image: mongo:4.4
    ports:
      - 27017:27017
    expose:
      - 27017
    #    environment:
    #      MONGO_INITDB_ROOT_USERNAME: root
    #      MONGO_INITDB_ROOT_PASSWORD: your_password
    #      MONGO_INITDB_DATABASE: books
    volumes:
      - /mongodb:/data/db
    restart: always

  rabbitmq:
    hostname: localhost
    container_name: rabbit-mq
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_ERLANG_COOKIE: "ABRKLMASLDASFAREDGKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "yourmqpasswordhere"
      RABBITMQ_DEFAULT_VHOST: "/"
  #    volumes:
  #      - ./rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro

  redis:
    hostname: localhost
    container_name: redis
    image: redis
    ports:
      - 6379:6379
    restart: always
    volumes:
      - ./data:/data
