version: '3.5'

services:
  rabbitmq:
    hostname: localhost
    container_name: rabbit-mq
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    restart: always

  redis:
    hostname: localhost
    container_name: redis
    image: redis
    ports:
      - 6379:6379
    restart: always
    volumes:
      - ./data:/data
