# Generated by Django 3.1.5 on 2021-02-03 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChessGame',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('white', models.IntegerField()),
                ('black', models.IntegerField()),
                ('competition_date', models.DateField()),
                ('created_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
