# Generated by Django 3.1.5 on 2021-02-08 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chessgame',
            name='black',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='chessgame',
            name='white',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='CompetitionResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner_id', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.chessgame')),
            ],
        ),
    ]
